### ISSUE TITLE
Let user rename themselves

### ISSUE THREAD

**Issue by Janiczek** [turboMaCk/planning-game#30]

**Comment by turboMaCk** [comment]
note: this will require to stop changing using names for referencing users

**Comment by turboMaCk** [comment]
this PR implements auto incremental ids https://github.com/turboMaCk/planning-game/pull/37

**Comment by turboMaCk** [comment]
this PR exposes player ids in API https://github.com/turboMaCk/planning-game/pull/43

**Comment by turboMaCk** [comment]
this PR exposes player ids in game snapshots data https://github.com/turboMaCk/planning-game/pull/46

**Comment by turboMaCk** [comment]
Last preparation step done: https://github.com/turboMaCk/planning-game/pull/47

now it should be fairly simple to implement rename functionality
