### ISSUE TITLE
Font doesn't load in card SVG

### ISSUE THREAD

**Issue by Janiczek** [turboMaCk/planning-game#39]
![font](https://user-images.githubusercontent.com/149425/55954095-10cc0c80-5c5e-11e9-99a1-7dd704fa4380.png)

Firefox, Linux.
I'm not sure why the card for `2` works :sweat_smile: 

This seems to be related to that issue on pro-next homepage (Reports book SVG image).

**Comment by turboMaCk** [comment]
writing sw for programmers is hard. too many bug reports:D
